"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue)\
$docker_context\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character"""

# =========palettes=========
# palette = '16c'
# palette = 'afternoon'
# palette = 'firefly'
# palette = 'forest'
# palette = 'ghost'
# palette = 'glow'
# palette = 'gray'
# palette = 'gruvbox'
# palette = 'neon'
# palette = 'pastel'
# palette = 'phoenix'
# palette = 'proton'
# palette = 'red'
# palette = 'screen'
# palette = 'sunrise'
# palette = 'gruvbox_dark'
palette = 'catppuccin_mocha'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.16c]
success_fg = 'green'
error_fg = 'red'
fg_1 = 'bright-white'
bg_1 = 'blue'
fg_2='bright-white'
bg_2='cyan'
fg_3 = 'bright-white'
bg_3 = 'green'
fg_4 = 'black'
bg_4 = 'bright-green'
fg_5 = 'black'
bg_5 = 'bright-yellow'
fg_6='black'
bg_6='yellow'

[palettes.afternoon]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#FFFF00'
bg_1 = '#2E3436'
fg_2='#FFFF00'
bg_2='#5F5F00'
fg_3 = '#FFFF00'
bg_3 = '#878700'
fg_4 = '#2E3436'
bg_4 = '#AFAF00'
fg_5 = '#2E3436'
bg_5 = '#D7D700'
fg_6='#2E3436'
bg_6='#FFFF00'

[palettes.firefly]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#00ff00'
bg_1 = '#2E3436'
fg_2='#00ff00'
bg_2='#005F00'
fg_3 = '#00ff00'
bg_3 = '#008700'
fg_4 = '#2E3436'
bg_4 = '#00AF00'
fg_5 = '#2E3436'
bg_5 = '#00D700'
fg_6='#2E3436'
bg_6='#00ff00'

[palettes.forest]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#00FFFF'
bg_1 = '#2E3436'
fg_2='#00FFFF'
bg_2='#005F5F'
fg_3 = '#00FFFF'
bg_3 = '#008787'
fg_4 = '#2E3436'
bg_4 = '#00AFAF'
fg_5 = '#2E3436'
bg_5 = '#00D7D7'
fg_6='#2E3436'
bg_6='#00FFFF'

[palettes.ghost]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#EEEEEE'
bg_1 = '#444444'
fg_2='#EEEEEE'
bg_2='#626262'
fg_3 = '#EEEEEE'
bg_3 = '#8A8A8A'
fg_4 = '#444444'
bg_4 = '#A8A8A8'
fg_5 = '#444444'
bg_5 = '#D0D0D0'
fg_6='#444444'
bg_6='#EEEEEE'

[palettes.glow]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#00ffff'
bg_1 = '#FF0000'
fg_2='#00ffff'
bg_2='#D75F5F'
fg_3 = '#00ffff'
bg_3 = '#8A8A8A'
fg_4 = '#FF0000'
bg_4 = '#87AFAF'
fg_5 = '#FF0000'
bg_5 = '#5FD7D7'
fg_6='#FF0000'
bg_6='#00ffff'

[palettes.gray]
success_fg = 'green'
error_fg = 'red'
fg_1 = 'white'
bg_1 = '8'
fg_2='8'
bg_2='7'
fg_3 = 'white'
bg_3 = '8'
fg_4 = '8'
bg_4 = '7'
fg_5 = 'white'
bg_5 = '8'
fg_6='8'
bg_6='7'

[palettes.gruvbox]
success_fg = '#00D700'
error_fg = 'red'
fg_1 = '#ffffff'
bg_1 = '#3c3836'
fg_2='#ffffff'
bg_2='#665c54'
fg_3 = '#ffffff'
bg_3 = '#458588'
fg_4 = '#ffffff'
bg_4 = '#689d6a'
fg_5 = '#ffffff'
bg_5 = '#d79921'
fg_6='#ffffff'
bg_6='#FF5F00'

[palettes.neon]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#00FF00'
bg_1 = '#FF0000'
fg_2='#00FF00'
bg_2='#D75F00'
fg_3 = '#00FF00'
bg_3 = '#AF8700'
fg_4 = '#FF0000'
bg_4 = '#87AF00'
fg_5 = '#FF0000'
bg_5 = '#5FD700'
fg_6='#FF0000'
bg_6='#00FF00'

[palettes.pastel]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#ffffff'
bg_1 = '#33658A'
fg_2='#ffffff'
bg_2='#06969A'
fg_3 = '#ffffff'
bg_3 = '#46A99A'
fg_4 = '#000000'
bg_4 = '#87AF87'
fg_5 = '#000000'
bg_5 = '#D8BB86'
fg_6='#000000'
bg_6='#FCA17D'

[palettes.phoenix]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#ffff00'
bg_1 = '#d70000'
fg_2='#ffff00'
bg_2='#d75f00'
fg_3 = '#ffff00'
bg_3 = '#FF8700'
fg_4 = '#d70000'
bg_4 = '#FFAF00'
fg_5 = '#d70000'
bg_5 = '#FFD700'
fg_6='#d70000'
bg_6='#ffff00'

[palettes.proton]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#00ffff'
bg_1 = '#0000ff'
fg_2='#00ffff'
bg_2='#005FFF'
fg_3 = '#00ffff'
bg_3 = '#0087FF'
fg_4 = '#0000ff'
bg_4 = '#00AFFF'
fg_5 = '#0000ff'
bg_5 = '#00D7FF'
fg_6='#0000ff'
bg_6='#00ffff'

[palettes.red]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#FFFFFF'
bg_1 = '#FF0000'
fg_2='#FFFFFF'
bg_2='#FF5F5F'
fg_3 = '#FFFFFF'
bg_3 = '#FF8787'
fg_4 = '#FF0000'
bg_4 = '#FFAFAF'
fg_5 = '#FF0000'
bg_5 = '#FFD7D7'
fg_6='#FF0000'
bg_6='#FFFFFF'

[palettes.screen]
success_fg = 'green'
error_fg = 'yellow'
fg_1 = 'white'
bg_1 = 'blue'
fg_2='black'
bg_2='cyan'
fg_3 = 'black'
bg_3 = 'green'
fg_4 = 'black'
bg_4 = 'bright-yellow'
fg_5 = 'black'
bg_5 = 'yellow'
fg_6='white'
bg_6='red'

[palettes.sunrise]
success_fg = 'green'
error_fg = 'red'
fg_1 = '#00FF00'
bg_1 = '#0000FF'
fg_2='#00FF00'
bg_2='#005FD7'
fg_3 = '#00FF00'
bg_3 = '#0087AF'
fg_4 = '#0000FF'
bg_4 = '#00AF87'
fg_5 = '#0000FF'
bg_5 = '#00D75F'
fg_6='#0000FF'
bg_6='#00FF00'

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Dev" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
